// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const fileMenu: string;
export const fileMenuOpen: string;
export const menuSection: string;
export const menuHeader: string;
export const menuList: string;
export const menuItem: string;
export const menuIcon: string;
export const menuItemText: string;
