// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const osdViewer: string;
export const homeButton: string;
export const zoomButton: string;
export const menuButton: string;
export const fullscreenButton: string;
