// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const zoomButtonDiv: string;
export const zoomButton: string;
export const zoomInButton: string;
export const zoomOutButton: string;
export const line: string;
